name: Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with maven
        run: mvn -B package -Dmaven.test.skip=true --file pom.xml

      - name: Rename the jar
        run: mv target/*.jar target/storelight.jar

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/sprint*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
