name: Build

on:
  push:
    branches: [rc]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with maven
        run: mvn -B package -Dmaven.test.skip=true --file pom.xml

      - name: Rename the jar
        run: mv target/*.jar target/storelight.jar

      - name: Upload the artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: storelight.jar
          path: target/storelight.jar
